### ISSUE TITLE
Remove use of `READ_COMMAND` in znode.g

### ISSUE THREAD

**Issue by markuspf** [gap-packages/ZeroMQInterface#12]

**Comment by fingolfin** [comment]
I think you can simply replace it by `READ_COMMAND_REAL` -- after all, these two functions only differ in their return values, and the zmq code ignores the return value.

**Comment by markuspf** [comment]
Resovled in dc5e7a985a4dc40b79734b5350cdb711413c0839 (and released in 0.7)
