### ISSUE TITLE
fail to LoadPackage("ZeroMQInterface") 

### ISSUE THREAD

**Issue by startxing** [gap-packages/ZeroMQInterface#35]
I have an issue to load the package "ZeroMQInterface". Below is what it shows:
![WX20240607-173925@2x](https://github.com/gap-packages/ZeroMQInterface/assets/172027287/bc6da6dc-ea83-4820-94e4-bf1d40e63d96)

**Comment by olexandr-konovalov** [comment]
@startxing thanks - could you please add which operating system do you use, which GAP distribution?

**Comment by fingolfin** [comment]
You need to compile the package as stated in the package manual. But first you need to install `zeromq`.

Looking at your screenshot, it seems you might be using https://github.com/gap-system/homebrew-gap which ideally would take care of stuff like that, but doesn't. Unfortunately it is unmaintained

**Comment by startxing** [comment]
> @startxing thanks - could you please add which operating system do you use, which GAP distribution?

I am using macOS Sonoma (version 14.1.1) and GAP version 4.12.2.

**Comment by startxing** [comment]
> You need to compile the package as stated in the package manual. But first you need to install `zeromq`.

Yes, 'zeromq' has been installed. But LoadPackage("zeromqinterface") fails.

> Looking at your screenshot, it seems you might be using https://github.com/gap-system/homebrew-gap which ideally would take care of stuff like that, but doesn't. Unfortunately it is unmaintained
Yes, I am using homebrew-gap to install gap.

**Comment by fingolfin** [comment]
To reiterate: you need to compile zeromqinterface

**Comment by startxing** [comment]
> To reiterate: you need to compile zeromqinterface

I did this (./configure; make). Still LoadPackage("zeromqinterface") fails.
![Uploading WX20240608-212148@2x.png…]()

**Comment by olexandr-konovalov** [comment]
@startxing I can't see the screenshot in the last comment.

**Comment by startxing** [comment]
> @startxing I can't see the screenshot in the last comment.

![WX20240608-212148@2x](https://github.com/gap-packages/ZeroMQInterface/assets/172027287/328b5cb6-0166-461b-8087-f2dfad3ba03c)

**Comment by fingolfin** [comment]
Instead of screen shots, could you please copy & paste the actual text?

you said you did run configure&&make for the package, but did they actually succeed? What is the output of those commands?

**Comment by olexandr-konovalov** [comment]
Moreover, the screenshot does not include the text above the `Packages` line which is also essential, e.g.
```
 ┌───────┐   GAP 4.13.0 of 2024-03-15
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-apple-darwin23-default64-kv9
 Configuration:  gmp 6.3.0, GASMAN, readline
 Loading the library and packages ...
```

**Comment by startxing** [comment]
```
> Last login: Sat Jun  8 21:04:40 on ttys005
> (base) startxing@Xins-MacBook-Pro-2 zeromqinterface % ./configure
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether the compiler supports GNU C... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to enable C11 features... none needed
> checking for GAP root directory... /Users/startxing/Downloads/gap
> checking for GAP architecture... checking for stdio.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for strings.h... yes
> checking for sys/stat.h... yes
> checking for sys/types.h... yes
> checking for unistd.h... yes
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for zmq.h... yes
> checking for ZMQ version >= 2.0.0... yes
> configure: creating ./config.status
> config.status: creating Makefile
> (base) startxing@Xins-MacBook-Pro-2 zeromqinterface % make
>    GAC     src/zmqgap.c => gen/src/zmqgap.o
>    GAC     gen/src/zmqgap.o => bin/x86_64-apple-darwin23-default64-kv9/zeromqinterface.so
> (base) startxing@Xins-MacBook-Pro-2 zeromqinterface % cd ../
> (base) startxing@Xins-MacBook-Pro-2 pkg % cd ../
> (base) startxing@Xins-MacBook-Pro-2 gap % cd ../
> (base) startxing@Xins-MacBook-Pro-2 Downloads % gap
>  ┌───────┐   GAP 4.12.2 of 2022-12-18
>  │  GAP  │   https://www.gap-system.org
>  └───────┘   Architecture: x86_64-apple-darwin23-default64-kv8
>  Configuration:  gmp 6.3.0, GASMAN, readline
>  Loading the library and packages ...
>  Packages:   AClib 1.3.2, Alnuth 3.2.1, AtlasRep 2.1.6, AutPGrp 1.11, 
>              Browse 1.8.19, CaratInterface 2.3.4, CRISP 1.4.6, 
>              crypting 0.10.4, Cryst 4.1.25, CrystCat 1.1.10, CTblLib 1.3.4, 
>              curlInterface 2.3.1, FactInt 1.6.3, FGA 1.4.0, Forms 1.2.9, 
>              GAPDoc 1.6.6, GBNP 1.0.5, genss 1.6.8, IO 4.8.0, IRREDSOL 1.4.4, 
>              json 2.1.1, LAGUNA 3.9.5, orb 4.9.0, Polenta 1.3.10, 
>              Polycyclic 2.16, PrimGrp 3.4.3, QPA 1.34, RadiRoot 2.9, 
>              recog 1.4.2, ResClasses 4.7.3, SmallGrp 1.5.1, Sophus 1.27, 
>              SpinSym 1.5.2, TomLib 1.2.9, TransGrp 3.6.3, utils 0.81, 
>              uuid 0.7
>  Try '??help' for help. See also '?copyright', '?cite' and '?authors'
> gap> LoadPackage("zeromqinterface");
> #I  ZeroMQInterface package is not available. To see further details, enter
> #I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
> fail
> gap> SetInfoLevel(InfoPackageLoading,4);
> gap> LoadPackage("zeromqinterface");
> #I  ZeroMQInterface: entering LoadPackage 
> #I  ZeroMQInterface: PackageAvailabilityInfo for version 0.14
> #I  ZeroMQInterface: PackageAvailabilityInfo: the AvailabilityTest function returned fail
> #I  ZeroMQInterface: PackageAvailabilityInfo: no installed version fits
> #I  ZeroMQInterface: return from LoadPackage, package is not available
> fail
> gap> 
```
Would this be okay?

**Comment by olexandr-konovalov** [comment]
Do you have another GAP installation? Are you sure that `gap` calls the GAP for which you have just compiled the package? What is the path to the directory in which you built the package, and what does `which gap` say? Or even more informative, try

    ls -la `which gap`

**Comment by startxing** [comment]
> Do you have another GAP installation? Are you sure that gap calls the GAP in which you have just compiled the package? 
> 
I am not sure.

>  what does which gap say?
> 
It says  /usr/local/bin/gap -> ../Cellar/gap/4.12.2/bin/gap

**Comment by olexandr-konovalov** [comment]
I've made a fresh installation of GAP 4.13.0 from https://github.com/gap-system/homebrew-gap and it works there. You may try to upgrade it as its README explains.

**Comment by startxing** [comment]
Thanks, @olexandr-konovalov and @fingolfin a lot! Now it works perfectly!
