### ISSUE TITLE
Remove the ZeroMQ code from hpcgap once this package is complete?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/ZeroMQInterface#5]
In an ideal world, this package would work under both classic and HPC-GAP (perhaps it already does, I did not yet test it). In that case, perhaps we can remove the ZeroMQ code from HPC-GAP. That would reduce the diffs between classic and HPC-GAP. It also fits with the vision of having a modular GAP core, with most functionality in it right now moved to packages.

**Comment by markuspf** [comment]
Yes, this should work, and was my plan also. At the moment there is almost no difference between the zeromq package code and the code that is in HPC-GAP, the only issues revolve around `#ifdef`ing out some details.
I'll make it a priority to make this work when I am at Sage days.

**Comment by fingolfin** [comment]
The code *was* removed some time ago.
